### ISSUE TITLE
Issue with script

### ISSUE THREAD

**Issue by DrakeDonnison** [XeroAPI/xero-python-oauth2-starter#39]
PS Z:\Code\Cleaned\Python Code\TapOnClock\xero-python-oauth2-app-master> & C:/Users/Drake/AppData/Local/Programs/Python/Python311/python.exe "z:/Code/Cleaned/Python Code/TapOnClock/xero-python-oauth2-app-master/app.py"
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:5000
Press CTRL+C to quit
127.0.0.1 - - [16/Aug/2023 16:47:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2023 16:47:48] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [16/Aug/2023 16:47:49] "GET /login HTTP/1.1" 302 -
C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_oauthlib\contrib\client\application.py:320: RuntimeWarning: OAUTHLIB_INSECURE_TRANSPORT has been found in os.environ but the app is not running in debug mode or testing mode. It may put you in danger of the Man-in-the-middle attack while using OAuth 2.
  warnings.warn(
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:356] Requesting url https://identity.xero.com/connect/token using method POST.
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:357] Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'authorization_code', 'code': 'ypCj9XAKicMwjY_xpfmb8JgIE2glNn12FYPhB3Y5oXA', 'client_id': 'A8B85346E4C64695945E88FC68939BDC', 'redirect_uri': 'http://localhost:5000/callback', 'client_secret': 'cSroX_YANXAbxZYwoh-m5K-bv7js-GXoiqyLY3VT21_qKlLx'}
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:358] Passing through key word arguments {'json': None, 'timeout': None, 'auth': None, 'verify': True, 'proxies': None}.
2023-08-16 16:48:13+1000 | DEBUG [urllib3.connectionpool.connectionpool.py:1003] Starting new HTTPS connection (1): identity.xero.com:443
2023-08-16 16:48:13+1000 | DEBUG [urllib3.connectionpool.connectionpool.py:456] https://identity.xero.com:443 "POST /connect/token HTTP/1.1" 200 2067
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:222] Prepared fetch token request body grant_type=authorization_code&code=ypCj9XAKicMwjY_xpfmb8JgIE2glNn12FYPhB3Y5oXA&client_id=A8B85346E4C64695945E88FC68939BDC&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fcallback&client_secret=cSroX_YANXAbxZYwoh-m5K-bv7js-GXoiqyLY3VT21_qKlLx
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:232] Request to fetch token completed with status 200.
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:234] Request headers were {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '238'}       
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:235] Request body was grant_type=authorization_code&code=ypCj9XAKicMwjY_xpfmb8JgIE2glNn12FYPhB3Y5oXA&client_id=A8B85346E4C64695945E88FC68939BDC&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fcallback&client_secret=cSroX_YANXAbxZYwoh-m5K-bv7js-GXoiqyLY3VT21_qKlLx
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:236] Response headers were {'Content-Type': 'application/json; charset=UTF-8', 'Server': 'nginx', 'Vary': 'Accept-Encoding', 'Xero-Origin-Id': 'IdentityServer.Web', 'Xero-Causation-Id': '2856034821dc4705a39f0e79f2ff0cfb', 'Xero-Message-Id': '63895a969b7b4d9bb236fe5d06412897', 'Xero-Activity-Id': 'ada57391bf044c0e948c189b9156f03a', 'Xero-Correlation-Id': '3d7c5ab3f4684f9684b48e660342795b', 'Content-Encoding': 'gzip', 'Content-Length': '2067', 'Expires': 'Wed, 16 Aug 2023 06:48:13 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Wed, 16 Aug 2023 06:48:13 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'Device=cd2dab02503a45c6a3274c0c2c61cde5; expires=Wed, 16 Aug 2028 06:48:13 GMT; path=/; samesite=none; httponly, _abck=7AAE31C4FACC61323A2AABB464CB2ADC~-1~YAAQNqgtF+5OWtaJAQAAphka/QoS2Dervc0gOJuE9GTYEhaZ0tPlem2LvqqDuDWJ4ypeJU3Se8bTsRQhjQU5PjHggIEEqLg+kiYESv1NNtqXLkuebeoqa4G0ds9PYgfawEWOh30wGAp2HbAYUF57y2uZxx44DSdQZyxj0AFqxa6sdRhYmM8x1M860MN2+m5NTL4H/ssRuQpw49atI3YQt65hDB8UjRH91DU86kCgDhB2HE0t7ZCwB8PpYHKYsQFfYs/TUlVueVRQMvndOUZd4CsipnqwH+oOyHK2VdQRvbwi3tKfglzsdiW3wjCfGYUSR/SlQNQ2N+PscNpNYYV0SiYG0SHrydu9yTtK5zCzdQk1WK/Le7lm~-1~-1~-1; Domain=.xero.com; Path=/; Expires=Thu, 15 Aug 2024 06:48:13 GMT; Max-Age=31536000; Secure, bm_sz=B02D371DBDAE5E37097C92BAACC6A855~YAAQNqgtF+9OWtaJAQAAphka/RTKItHUsw6PfgNe+Y3wmhCI+nnHcs4z18ZhVyWpXhEqbJQ4UrGVBnzOzQ2e5ZqFR3gBz8qH/dLkF9fOmfFUkCft/M/ldSMtNMLZrYBRLg3mkljMn2m3g0kkuSMFkyAxNfmwToX4SC4RZh7C7PDRBpNoMPqAjDW9+9bHV32LshikqQO7Z6w9GLuQ6MV/VwblV1YrLV6j/0woQmCw5kjY9ylM4N5Hz4WcDK/ioPzt+W0rzbhX06LpJcC+9j4GpxpPoFuMYRuwcF/MX9FLq9Ie~3225142~4338740; Domain=.xero.com; Path=/; Expires=Wed, 16 Aug 2023 10:48:13 GMT; Max-Age=14400'} and content {"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjFDQUY4RTY2NzcyRDZEQzAyOEQ2NzI2RkQwMjYxNTgxNTcwRUZDMTkiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJISy1PWm5jdGJjQW8xbkp2MENZVmdWY09fQmsifQ.eyJuYmYiOjE2OTIxNjg0OTMsImV4cCI6MTY5MjE2ODc5MywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS54ZXJvLmNvbSIsImF1ZCI6IkE4Qjg1MzQ2RTRDNjQ2OTU5NDVFODhGQzY4OTM5QkRDIiwiaWF0IjoxNjkyMTY4NDkzLCJhdF9oYXNoIjoiZ01tNDNvTE1LSlhXUHlRaGlodHdpdyIsInNfaGFzaCI6Im1tcUhfRk9lVldOZ041Mmtkdmt6SkEiLCJzaWQiOiJhNzcxMGM2ZjJkNmY0NDg4OGQ0ZTEyYzkwOTJhNDhhYyIsInN1YiI6IjlkNWYwNDhmZTU5OTVhZTM5ZTg2NWZiZmUwNTFkODRhIiwiYXV0aF90aW1lIjoxNjkyMTY4NDgxLCJ4ZXJvX3VzZXJpZCI6IjkzOWRmZDRkLWEzNWEtNDkwNC1hNGQ2LTFlYjY0M2ViOTdlYSIsImdsb2JhbF9zZXNzaW9uX2lkIjoiYTc3MTBjNmYyZDZmNDQ4ODhkNGUxMmM5MDkyYTQ4YWMiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJsanNhd3RlbGxAZ21haWwuY29tIiwiZW1haWwiOiJsanNhd3RlbGxAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IkxhdXJlbiIsImZhbWlseV9uYW1lIjoiU2F3dGVsbCIsIm5hbWUiOiJMYXVyZW4gU2F3dGVsbCIsImFtciI6WyJwd2QiXX0.mPFLjfNKnJftAPACqGl-g0yBz91ERyHbeqx1Y556-04huqHV6I48Cevje-fQYxf12SIpVu4zthJbHvSCBuunaAflx69m6VTAMHNkSEfzKTJoRjDAYiRKjhD6bTUbcqtz3pZpre45ZdBHn62M55g7Q3ZVFIrFw8S1qyvDAJ2MNgDcF0jIk-jXKQDTotOEcMmHngRRttJO05TQoo_Z2rW7wpFPzIMkgS-1447zrmiP6jdz3maIcTy2cFGcL1Es38G6TrdjxKJ5AjfWozE5peyIsx-m0Y-FgjfIaK66uZXqnZlFHPLth8EDIWeL8WrZWP4qqspY2Q3jtsPnaHyFA83FkA","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjFDQUY4RTY2NzcyRDZEQzAyOEQ2NzI2RkQwMjYxNTgxNTcwRUZDMTkiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJISy1PWm5jdGJjQW8xbkp2MENZVmdWY09fQmsifQ.eyJuYmYiOjE2OTIxNjg0OTMsImV4cCI6MTY5MjE3MDI5MywiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS54ZXJvLmNvbSIsImF1ZCI6Imh0dHBzOi8vaWRlbnRpdHkueGVyby5jb20vcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoiQThCODUzNDZFNEM2NDY5NTk0NUU4OEZDNjg5MzlCREMiLCJzdWIiOiI5ZDVmMDQ4ZmU1OTk1YWUzOWU4NjVmYmZlMDUxZDg0YSIsImF1dGhfdGltZSI6MTY5MjE2ODQ4MSwieGVyb191c2VyaWQiOiI5MzlkZmQ0ZC1hMzVhLTQ5MDQtYTRkNi0xZWI2NDNlYjk3ZWEiLCJnbG9iYWxfc2Vzc2lvbl9pZCI6ImE3NzEwYzZmMmQ2ZjQ0ODg4ZDRlMTJjOTA5MmE0OGFjIiwic2lkIjoiYTc3MTBjNmYyZDZmNDQ4ODhkNGUxMmM5MDkyYTQ4YWMiLCJqdGkiOiJBMzlCQzkzRjU4MkJCMzFCQTNFOEUwMEE5MEQ3NjA2NyIsImF1dGhlbnRpY2F0aW9uX2V2ZW50X2lkIjoiNWUxY2QzMzAtMDdmZS00ZjgzLThlYWMtN2NmNzU0OThmYzEyIiwic2NvcGUiOlsiZW1haWwiLCJwcm9maWxlIiwib3BlbmlkIiwiYWNjb3VudGluZy5yZXBvcnRzLnJlYWQiLCJhY2NvdW50aW5nLmF0dGFjaG1lbnRzLnJlYWQiLCJmaWxlcyIsInBheXJvbGwuZW1wbG95ZWVzIiwicGF5cm9sbC5lbXBsb3llZXMucmVhZCIsInBheXJvbGwucGF5cnVucyIsInBheXJvbGwucGF5c2xpcCIsInBheXJvbGwudGltZXNoZWV0cyIsInBheXJvbGwudGltZXNoZWV0cy5yZWFkIiwicHJvamVjdHMiLCJhY2NvdW50aW5nLnNldHRpbmdzIiwiYWNjb3VudGluZy5zZXR0aW5ncy5yZWFkIiwiYWNjb3VudGluZy5hdHRhY2htZW50cyIsImFjY291bnRpbmcudHJhbnNhY3Rpb25zIiwiYWNjb3VudGluZy5qb3VybmFscy5yZWFkIiwiYWNjb3VudGluZy50cmFuc2FjdGlvbnMucmVhZCIsImFzc2V0cyIsImFjY291bnRpbmcuY29udGFjdHMiLCJhY2NvdW50aW5nLmNvbnRhY3RzLnJlYWQiLCJwYXlyb2xsLnNldHRpbmdzIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdfQ.FDNSSD_sR8GkDYnESbVz-MATAPEemkIY7DTscAFhJH0mgFclNJ0bC4bUALoikVGahtktbreeTPZfa3tvCqI44aNI7dWTNm53a1UZhRmWGp1J2l21GLt4CN9Xsq_L710Tv_xxQHmHF2qH5KdjpFNNF2b7xjjWecPi-bSUQL6U2OYBpV46SN-evjFQR-s5HBhugwWJ5wFE2rhWQUZxD9YTTmd5X6Q8TcRujie2GoH68OTALENv5TI49eeXoVqQdt27JObxrUBMK10uK1_A37EIBwL0gzX1vykmGq9FjC7BcnBumzEcK8-UgKeLKYAQ50aDL3Mwnjxpe6SpsGaD-yyBQA","expires_in":1800,"token_type":"Bearer","refresh_token":"Ua1XKeGm6zwpgoXEHnBO9S8yWkSNixlz6P9mZQbOaY0","scope":"openid profile email accounting.transactions accounting.transactions.read accounting.reports.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read assets projects files payroll.employees payroll.payruns payroll.payslip payroll.timesheets payroll.settings offline_access payroll.timesheets.read payroll.employees.read"}.
2023-08-16 16:48:13+1000 | DEBUG [requests_oauthlib.oauth2_session.oauth2_session.py:238] Invoking 0 token response hooks.
Scope has changed from "email accounting.transactions.read accounting.contacts files payroll.settings profile accounting.attachments.read accounting.settings.read payroll.payruns accounting.settings accounting.attachments accounting.contacts.read offline_access projects accounting.journals.read assets accounting.reports.read payroll.employees accounting.transactions payroll.payslip payroll.timesheets openid" to "payroll.employees.read email accounting.transactions.read accounting.contacts files payroll.settings profile accounting.attachments.read accounting.settings.read payroll.payruns accounting.settings accounting.attachments accounting.contacts.read offline_access projects accounting.journals.read payroll.timesheets.read assets accounting.reports.read payroll.employees accounting.transactions payroll.payslip payroll.timesheets openid".
[2023-08-16 16:48:13,683] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "z:\Code\Cleaned\Python Code\TapOnClock\xero-python-oauth2-app-master\app.py", line 12479, in oauth_callback
    response = xero.authorized_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_oauthlib\contrib\client\application.py", line 267, in authorized_response
    token = oauth.fetch_token(
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests_oauthlib\oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 411, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 379, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\Drake\AppData\Local\Programs\Python\Python311\Lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 409, in validate_token_parameters
    raise w
Warning: Scope has changed from "email accounting.transactions.read accounting.contacts files payroll.settings profile accounting.attachments.read accounting.settings.read payroll.payruns accounting.settings accounting.attachments accounting.contacts.read offline_access projects accounting.journals.read assets accounting.reports.read payroll.employees accounting.transactions payroll.payslip payroll.timesheets openid" to "payroll.employees.read email accounting.transactions.read accounting.contacts files payroll.settings profile accounting.attachments.read accounting.settings.read payroll.payruns accounting.settings accounting.attachments accounting.contacts.read offline_access projects accounting.journals.read payroll.timesheets.read assets accounting.reports.read payroll.employees accounting.transactions payroll.payslip payroll.timesheets openid".
127.0.0.1 - - [16/Aug/2023 16:48:13] "GET /callback?code=ypCj9XAKicMwjY_xpfmb8JgIE2glNn12FYPhB3Y5oXA&scope=openid%20profile%20email%20accounting.transactions%20accounting.transactions.read%20accounting.reports.read%20accounting.journals.read%20accounting.settings%20accounting.settings.read%20accounting.contacts%20accounting.contacts.read%20accounting.attachments%20accounting.attachments.read%20assets%20projects%20files%20payroll.employees%20payroll.payruns%20payroll.payslip%20payroll.timesheets%20payroll.settings%20offline_access&state=yfgvoeafal&session_state=4nKrAAvXlgw73nOPpH6GW76nZSPv9ir746RHwKMvmuY.qzNunxDNjr2pSDNjJ8vSEw HTTP/1.1" 500 -

**Comment by DrakeDonnison** [comment]
Found it 
Warning: Scope has changed from 
"email accounting.transactions.read accounting.contacts files payroll.settings profile accounting.attachments.read accounting.settings.read payroll.payruns accounting.settings accounting.attachments accounting.contacts.read offline_access projects accounting.journals.read assets accounting.reports.read payroll.employees accounting.transactions payroll.payslip payroll.timesheets openid" 
to 
"payroll.employees.read email accounting.transactions.read accounting.contacts files payroll.settings profile accounting.attachments.read accounting.settings.read payroll.payruns accounting.settings accounting.attachments accounting.contacts.read offline_access projects accounting.journals.read payroll.timesheets.read assets accounting.reports.read payroll.employees accounting.transactions payroll.payslip payroll.timesheets openid".
